version: 0.1
phases:
  install:
    commands:
      - npm install time
      - aws cloudformation package \
         --template-file template.yaml \
         --s3-bucket pull-request-builder-service \
         --output-template-file resources.yaml
artifacts:
  type: zip
  files:
    - resources.yaml
